### ISSUE TITLE
error: Failed to load ressource

### ISSUE THREAD

**Issue by tfeige91** [expfactory-experiments/kirby#1]
The kirby (as it is here) - executed locally (just opening the index.html) produces the following error for me (using chrome/safari):
[kirby locally.log](https://github.com/expfactory-experiments/kirby/files/5451116/kirby.locally.log)

I attach the log. 

The tests however starts and can be used locally but the error seems to lead to a server timeout when used with expfactory.

This is super strange and I don't understand what is happening here :D 
[kirby server.log](https://github.com/expfactory-experiments/kirby/files/5451118/kirby.server.log)

To make it even more hard to understand: It worked until earlier this week (on the server). 
Maybe one of the expfactory-components changed? 

I also attach the dockerfile I use.

Dockerfile: 
`FROM quay.io/vanessa/expfactory-builder:base

########################################
# Configure
########################################

ENV EXPFACTORY_STUDY_ID expfactory
ENV EXPFACTORY_SERVER localhost
ENV EXPFACTORY_CONTAINER true
ENV EXPFACTORY_DATA /scif/data
ENV EXPFACTORY_DATABASE filesystem
ENV EXPFACTORY_HEADLESS false
ENV EXPFACTORY_BASE /scif/apps
 
ADD startscript.sh /startscript.sh
RUN chmod u+x /startscript.sh

WORKDIR /opt 
RUN git clone -b fix/wekzerg-version https://www.github.com/expfactory/expfactory
WORKDIR expfactory 
RUN cp script/nginx.gunicorn.conf /etc/nginx/sites-enabled/default && \
    cp script/nginx.conf /etc/nginx/nginx.conf
RUN mkdir -p /scif/data # saved data
RUN mkdir -p /scif/apps # experiments 
RUN mkdir -p /scif/logs # gunicorn logs 
RUN python3 -m pip install gunicorn
RUN cp expfactory/config_dummy.py expfactory/config.py && \
    chmod u+x /opt/expfactory/script/generate_key.sh && \
    /bin/bash /opt/expfactory/script/generate_key.sh /opt/expfactory/expfactory/config.py
RUN python3 setup.py install
RUN python3 -m pip install pyaml    pymysql psycopg2==2.7.5
RUN apt-get clean          # tests, mysql,  postgres

########################################
# Experiments
########################################

LABEL EXPERIMENT_code /scif/apps/code
ADD code /scif/apps/code
WORKDIR /scif/apps
RUN expfactory install code

LABEL EXPERIMENT_simple-reaction-time /scif/apps/simple-reaction-time
ADD simple-reaction-time /scif/apps/simple-reaction-time
WORKDIR /scif/apps
RUN expfactory install simple-reaction-time

LABEL EXPERIMENT_go-nogo /scif/apps/go-nogo
ADD go-nogo /scif/apps/go-nogo
WORKDIR /scif/apps
RUN expfactory install go-nogo

LABEL EXPERIMENT_n-back /scif/apps/n-back
ADD n-back /scif/apps/n-back
WORKDIR /scif/apps
RUN expfactory install n-back

LABEL EXPERIMENT_tower-of-london /scif/apps/tower-of-london
ADD tower-of-london /scif/apps/tower-of-london
WORKDIR /scif/apps
RUN expfactory install tower-of-london

LABEL EXPERIMENT_flanker /scif/apps/flanker
ADD flanker /scif/apps/flanker
WORKDIR /scif/apps
RUN expfactory install flanker

LABEL EXPERIMENT_kirby /scif/apps/kirby
ADD kirby /scif/apps/kirby
WORKDIR /scif/apps
RUN expfactory install kirby

LABEL EXPERIMENT_bart /scif/apps/bart
ADD bart /scif/apps/bart
WORKDIR /scif/apps
RUN expfactory install bart

LABEL EXPERIMENT_information-sampling /scif/apps/information-sampling
ADD information-sampling /scif/apps/information-sampling
WORKDIR /scif/apps
RUN expfactory install information-sampling

LABEL EXPERIMENT_judgement-of-line-orientation-test /scif/apps/judgement-of-line-orientation-test
ADD judgement-of-line-orientation-test /scif/apps/judgement-of-line-orientation-test
WORKDIR /scif/apps
RUN expfactory install judgement-of-line-orientation-test

LABEL EXPERIMENT_reversal-learning /scif/apps/reversal-learning
ADD reversal-learning /scif/apps/reversal-learning
WORKDIR /scif/apps
RUN expfactory install reversal-learning

LABEL EXPERIMENT_stroop /scif/apps/stroop
ADD stroop /scif/apps/stroop
WORKDIR /scif/apps
RUN expfactory install stroop

LABEL EXPERIMENT_stop-signal /scif/apps/stop-signal
ADD stop-signal /scif/apps/stop-signal
WORKDIR /scif/apps
RUN expfactory install stop-signal

ENTRYPOINT ["/bin/bash", "/startscript.sh"]
EXPOSE 5000
EXPOSE 80
EXPOSE 3391
`

**Comment by vsoch** [comment]
Hey @tfeige91 ! Let's start with the issue in the browser. I tested for Firefox (no errors in the console) and then Chrome (I reproduced your issues) and for the latter, regardless of the error it seemed to function without issue. So, a first option is just to use Firefox, or be okay with having the messages in the console with Chrome. If you want to take a shot at fixing chrome, likely we just need to try following the instructions and reloading the audio context (see here https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio) but then you'd need to check for the browser being used and make sure it's chrome. The last errors appear to be missing .map files, which could easily be added to the repository! Do you want to try some of these out and do a PR to the repository? I'd be happy to add any fixes.

**Comment by tfeige91** [comment]
Hi Vanessa,
I solved the issue by removing the divs from preloading but loading them inside the plugin.
Since the kirby is not time-sensitive I guess we can go with that. 

I'm not a hundred percent sure though what exactly was the problem the html-preloading was causing on the server.

**Comment by vsoch** [comment]
Great! If you think the experiment is better and others would benefit from your changes, please open a PR.
